global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DocParser API Server
  - job_name: 'docparser-api'
    static_configs:
      - targets: ['docparser-api:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # DocParser Workers
  - job_name: 'docparser-workers'
    static_configs:
      - targets: ['docparser-worker-1:8080', 'docparser-worker-2:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Temporal Server (if metrics are exposed)
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']
    scrape_interval: 30s

  # PostgreSQL (using postgres_exporter if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
